server:
  port: 8080

spring:
  application:
    name: springboot-swagger-v3-example

springfox:
  documentation:
    swagger-ui:
      enabled: true

#    預設url http://localhost:8080/swagger-ui/index.html